### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by echtelerp** [Proxx/Grafana-armv7#2]
Hi Proxx, 

i have a quick question to you, how did you manage to set up a automated build, that can run on x86, as well as arm? 
I somehow manage only to get It running on x86

cheers, Philipp

**Comment by Proxx** [comment]
It sould not work on x86. step 3 of the docker file:

RUN wget -O /tmp/grafana.tar.gz https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.2.linux-armv7.tar.gz

It downloads the armv7 binaries.

What is the output of docker when running the Dockerfile on arm?

**Comment by Proxx** [comment]
Now i get the problem, the website got multiple binaries for arm i think the script parses the website and fetched the wrong binary, i will do some tests tomorrow

**Comment by echtelerp** [comment]
Hi Proxx, 
I tested the Container on my mac and on a raspberry pi 3+. 
Both worked perfectly :-) 
so whatever you did, was great, following the multi arch approach of docker. 
I have not testet the container on windows jet, but will soon. 
I saw, you did not create a automated build, so i guess, you build the container on a arm platform your self and uploaded it to the hub.

**Comment by Proxx** [comment]
yes i have a cronjob script on my RPI3b+ that checks, builds and pushes new versions to the dockerhub. but specifically for armv7 not multiarch. it shouldn't work, i tested it on windows and it doesn't.
(ps: i do not have a Mac to test, but since the build-dockerfile.sh is specifically searching for armv7 i doubt that it works on a mac)

maybe i could make the process multiarch but i specifically did not!
I think it would be better to use the native [grafana/grafana](https://hub.docker.com/r/grafana/grafana/) tag for x86/x64 instead of my homebrew script.

could you post the dockerfile contents used for the build or the build log itself so i could try to explain the situation?

**Comment by echtelerp** [comment]
Okay, than i can Skip testing it on windows. 
Have you tried to change the Container to another base Image?

**Comment by Proxx** [comment]
@echtelerp im not sure what you are aiming for. the build script is generating a armv7 Dockerfile and that Dockerfile is working flawless on my RPI3B+ 
i'm using the official base images of debian just to be sure no one messed with the OS before i added the grafana binaries.

this project is not aiming to make a multiarch docker image, 

if you like to run grafana on other platforms like x86/x64 i really suggest using the official (grafana) repo like i recommended before.

i would really like to help you if there are problems generating/running the Dockerfile, but i cannot help you any further unless you are more specific about the problem

@echtelerp since you did not respond in a fashionable time, i will close this ticket.
